apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akhq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/devoteam6342406/argocd-kafka.git
    targetRevision: HEAD
    path: akhq
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
