apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      labels:
        app: akhq
    spec:
      containers:
        - name: akhq
          image: tchiotludo/akhq:latest
          ports:
            - containerPort: 8085
          volumeMounts:
            - name: config-volume
              mountPath: /app/application.yml
              subPath: application.yml
      volumes:
        - name: config-volume
          configMap:
            name: akhq-config
