apiVersion: v1
kind: Service
metadata:
  name: akhq
  namespace: kafka
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app: akhq
